# Generated by Django 2.1.3 on 2018-11-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20181113_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_field', to='management.RiskField'),
        ),
    ]
