# Generated by Django 2.1.3 on 2018-11-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20181113_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskvalue',
            name='risk',
        ),
        migrations.AddField(
            model_name='riskvalue',
            name='risk_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_field_value', to='management.RiskField'),
        ),
    ]
