# Generated by Django 2.1.3 on 2018-11-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20181115_0109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskValue',
        ),
    ]
